// Datos compartidos de propiedades para usar en toda la aplicación

export interface Property {
  id: string;
  title: string;
  price: number;
  pricePerM2: number;
  location: string;
  propertyType:
    | 'apartment'
    | 'house'
    | 'condo'
    | 'penthouse'
    | 'duplex'
    | 'studio'
    | 'land'
    | 'commercial'
    | 'warehouse'
    | 'office'
    | 'garage'
    | 'storage';
  operation: 'sale' | 'rent';

  // Características principales
  constructedArea: number;
  usableArea: number;
  bedrooms: number;
  bathrooms: number;
  floor?: string;

  // Detalles adicionales
  yearBuilt?: number;
  condition?: 'new' | 'good' | 'to-renovate';
  orientation?: string;
  energyCertification?: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'pending';

  // Equipamiento
  hasElevator?: boolean;
  hasAirConditioning?: boolean;
  hasHeating?: boolean;
  heatingType?: string;
  hasParking?: boolean;
  hasStorage?: boolean;
  hasTerrace?: boolean;
  hasBalcony?: boolean;
  hasGarden?: boolean;
  hasPool?: boolean;
  hasBuiltInWardrobes?: boolean;
  isFurnished?: boolean;
  isAccessible?: boolean;

  // Descripción y multimedia
  description?: string;
  socialLinks?: {
    instagram?: { url: string; likes: number; comments: number };
    facebook?: { url: string; likes: number; comments: number };
    youtube?: { url: string; likes: number; comments: number };
    tiktok?: { url: string; likes: number; comments: number };
  };
  images: string[];

  // Metadata
  status: 'available' | 'unavailable' | 'sold' | 'rented' | 'reserved';
  updatedAt: string;
  idealistaUrl?: string;

  // Estadísticas de Idealista (solo si está conectado a Idealista)
  idealistaStats?: {
    views: number; // Visitas
    contacts: number; // Contactos
    favorites: number; // Favoritos
    searchPosition?: number; // Posición en búsqueda (opcional)
  };

  // Marca de agua
  watermarkEnabled?: boolean;
  watermarkPosition?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'center';
  watermarkSize?: 'xs' | 's' | 'm' | 'l' | 'xl';
  watermarkOpacity?: number;
  watermarkRotation?: number;
  watermarkCustomPosition?: { x: number; y: number };
  watermarkWidth?: number;

  // Interesados
  interestedCount?: number;
  interestedLeads?: {
    id: string;
    name: string;
    phone: string;
    email?: string;
    avatarUrl?: string;
    lastContact: string;
    qualification: number;
    source?: 'whatsapp' | 'instagram' | 'messenger' | 'tiktok';
  }[];
}

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop-001',
    title: 'Casa de lujo con jardín',
    price: 850000,
    pricePerM2: 3542,
    location: 'Pozuelo de Alarcón, Madrid',
    propertyType: 'house',
    operation: 'sale',
    constructedArea: 240,
    usableArea: 210,
    bedrooms: 4,
    bathrooms: 3,
    floor: 'Planta baja + 1',
    yearBuilt: 2020,
    condition: 'good',
    orientation: 'Sur',
    energyCertification: 'B',
    hasElevator: false,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Suelo radiante',
    hasParking: true,
    hasStorage: true,
    hasTerrace: false,
    hasBalcony: false,
    hasGarden: true,
    hasPool: true,
    hasBuiltInWardrobes: true,
    isFurnished: false,
    isAccessible: true,
    description:
      'Magnifica casa unifamiliar en zona residencial premium. Amplios espacios, acabados de primera calidad y excelente orientación. Jardín privado con piscina, ideal para familias. Cerca de colegios internacionales y centros comerciales.',
    socialLinks: {
      instagram: { url: 'https://www.instagram.com/reel/example1', likes: 8947, comments: 456 },
      facebook: { url: 'https://www.facebook.com/video/casa-pozuelo', likes: 5623, comments: 312 },
      youtube: { url: 'https://www.youtube.com/watch?v=example1', likes: 3876, comments: 234 },
      tiktok: { url: 'https://www.tiktok.com/@example/casa-pozuelo', likes: 24587, comments: 1043 },
    },
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&q=80',
    ],
    status: 'unavailable',
    updatedAt: '2024-01-15T10:30:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example1',
    idealistaStats: {
      views: 3567,
      contacts: 142,
      favorites: 256,
    },
    interestedCount: 25,
    interestedLeads: [
      {
        id: 'lead-001',
        name: 'María García',
        phone: '+34 600 270327',
        email: 'maria.garcia@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2Mjk2NzU1MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-15',
        qualification: 95,
        source: 'whatsapp',
      },
      {
        id: 'lead-002',
        name: 'Carlos Fernández',
        phone: '+34 601 786132',
        email: 'carlos.f@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-14',
        qualification: 88,
        source: 'instagram',
      },
      {
        id: 'lead-003',
        name: 'Laura Martínez',
        phone: '+34 602 607380',
        email: 'laura.m@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1525786210598-d527194d3e9a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMHdvbWFuJTIwc21pbGluZ3xlbnwxfHx8fDE3NjI5Njc3MzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-13',
        qualification: 82,
        source: 'messenger',
      },
      {
        id: 'lead-004',
        name: 'David Sánchez',
        phone: '+34 603 905881',
        avatarUrl:
          'https://images.unsplash.com/photo-1420310414923-bf3651a89816?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzc21hbiUyMHByb2Zlc3Npb25hbHxlbnwxfHx8fDE3NjMwMTg2MjF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-12',
        qualification: 76,
        source: 'tiktok',
      },
      {
        id: 'lead-005',
        name: 'Ana López',
        phone: '+34 604 335435',
        email: 'ana.lopez@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1675663351050-89949e051c38?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmZW1hbGUlMjBleGVjdXRpdmUlMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjMwMjY3NDR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-11',
        qualification: 90,
        source: 'whatsapp',
      },
      {
        id: 'lead-006',
        name: 'Roberto Díaz',
        phone: '+34 605 123456',
        email: 'roberto.d@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-10',
        qualification: 85,
        source: 'instagram',
      },
      {
        id: 'lead-007',
        name: 'Patricia Ruiz',
        phone: '+34 606 234567',
        email: 'patricia.r@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1525786210598-d527194d3e9a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMHdvbWFuJTIwc21pbGluZ3xlbnwxfHx8fDE3NjI5Njc3MzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-09',
        qualification: 78,
        source: 'messenger',
      },
      {
        id: 'lead-008',
        name: 'Javier Morales',
        phone: '+34 607 345678',
        avatarUrl:
          'https://images.unsplash.com/photo-1420310414923-bf3651a89816?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzc21hbiUyMHByb2Zlc3Npb25hbHxlbnwxfHx8fDE3NjMwMTg2MjF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-08',
        qualification: 92,
        source: 'tiktok',
      },
      {
        id: 'lead-009',
        name: 'Isabel Romero',
        phone: '+34 608 456789',
        email: 'isabel.r@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2Mjk2NzU1MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-07',
        qualification: 87,
        source: 'whatsapp',
      },
      {
        id: 'lead-010',
        name: 'Miguel Ángel Torres',
        phone: '+34 609 567890',
        email: 'miguel.torres@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-06',
        qualification: 81,
        source: 'instagram',
      },
      {
        id: 'lead-011',
        name: 'Carmen Vega',
        phone: '+34 610 678901',
        email: 'carmen.v@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1675663351050-89949e051c38?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmZW1hbGUlMjBleGVjdXRpdmUlMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjMwMjY3NDR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-05',
        qualification: 89,
        source: 'messenger',
      },
      {
        id: 'lead-012',
        name: 'Francisco Jiménez',
        phone: '+34 611 789012',
        avatarUrl:
          'https://images.unsplash.com/photo-1420310414923-bf3651a89816?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzc21hbiUyMHByb2Zlc3Npb25hbHxlbnwxfHx8fDE3NjMwMTg2MjF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-04',
        qualification: 74,
        source: 'tiktok',
      },
      {
        id: 'lead-013',
        name: 'Raquel Navarro',
        phone: '+34 612 890123',
        email: 'raquel.n@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1525786210598-d527194d3e9a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMHdvbWFuJTIwc21pbGluZ3xlbnwxfHx8fDE3NjI5Njc3MzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-03',
        qualification: 86,
        source: 'whatsapp',
      },
      {
        id: 'lead-014',
        name: 'Antonio Castillo',
        phone: '+34 613 901234',
        email: 'antonio.c@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-02',
        qualification: 79,
        source: 'instagram',
      },
      {
        id: 'lead-015',
        name: 'Silvia Hernández',
        phone: '+34 614 012345',
        email: 'silvia.h@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2Mjk2NzU1MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-01',
        qualification: 91,
        source: 'messenger',
      },
      {
        id: 'lead-016',
        name: 'Juan Carlos Ortega',
        phone: '+34 615 123456',
        avatarUrl:
          'https://images.unsplash.com/photo-1420310414923-bf3651a89816?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzc21hbiUyMHByb2Zlc3Npb25hbHxlbnwxfHx8fDE3NjMwMTg2MjF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2024-12-31',
        qualification: 83,
        source: 'tiktok',
      },
      {
        id: 'lead-017',
        name: 'Teresa Gil',
        phone: '+34 616 234567',
        email: 'teresa.g@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1675663351050-89949e051c38?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmZW1hbGUlMjBleGVjdXRpdmUlMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjMwMjY3NDR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2024-12-30',
        qualification: 88,
        source: 'whatsapp',
      },
      {
        id: 'lead-018',
        name: 'Alberto Serrano',
        phone: '+34 617 345678',
        email: 'alberto.s@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2024-12-29',
        qualification: 77,
        source: 'instagram',
      },
      {
        id: 'lead-019',
        name: 'Mónica Delgado',
        phone: '+34 618 456789',
        email: 'monica.d@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1525786210598-d527194d3e9a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMHdvbWFuJTIwc21pbGluZ3xlbnwxfHx8fDE3NjI5Njc3MzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2024-12-28',
        qualification: 84,
        source: 'messenger',
      },
      {
        id: 'lead-020',
        name: 'Sergio Pascual',
        phone: '+34 619 567890',
        avatarUrl:
          'https://images.unsplash.com/photo-1420310414923-bf3651a89816?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzc21hbiUyMHByb2Zlc3Npb25hbHxlbnwxfHx8fDE3NjMwMTg2MjF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2024-12-27',
        qualification: 80,
        source: 'tiktok',
      },
      {
        id: 'lead-021',
        name: 'Elena Montero',
        phone: '+34 620 678901',
        email: 'elena.m@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2Mjk2NzU1MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2024-12-26',
        qualification: 94,
        source: 'whatsapp',
      },
      {
        id: 'lead-022',
        name: 'Fernando Méndez',
        phone: '+34 621 789012',
        email: 'fernando.m@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2024-12-25',
        qualification: 75,
        source: 'instagram',
      },
      {
        id: 'lead-023',
        name: 'Cristina Prieto',
        phone: '+34 622 890123',
        email: 'cristina.p@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1675663351050-89949e051c38?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmZW1hbGUlMjBleGVjdXRpdmUlMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjMwMjY3NDR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2024-12-24',
        qualification: 82,
        source: 'messenger',
      },
      {
        id: 'lead-024',
        name: 'Raúl Vargas',
        phone: '+34 623 901234',
        avatarUrl:
          'https://images.unsplash.com/photo-1420310414923-bf3651a89816?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzc21hbiUyMHByb2Zlc3Npb25hbHxlbnwxfHx8fDE3NjMwMTg2MjF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2024-12-23',
        qualification: 86,
        source: 'tiktok',
      },
      {
        id: 'lead-025',
        name: 'Beatriz Campos',
        phone: '+34 624 012345',
        email: 'beatriz.c@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1525786210598-d527194d3e9a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMHdvbWFuJTIwc21pbGluZ3xlbnwxfHx8fDE3NjI5Njc3MzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2024-12-22',
        qualification: 89,
        source: 'whatsapp',
      },
    ],
  },
  {
    id: 'prop-many-photos',
    title: 'Villa de diseño con galería completa',
    price: 1250000,
    pricePerM2: 4167,
    location: 'La Moraleja, Madrid',
    propertyType: 'house',
    operation: 'sale',
    constructedArea: 300,
    usableArea: 280,
    bedrooms: 5,
    bathrooms: 4,
    floor: 'Planta baja + 2',
    yearBuilt: 2022,
    condition: 'new',
    orientation: 'Sur',
    energyCertification: 'A',
    hasElevator: false,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Geotérmica',
    hasParking: true,
    hasStorage: true,
    hasTerrace: true,
    hasBalcony: true,
    hasGarden: true,
    hasPool: true,
    hasBuiltInWardrobes: true,
    isFurnished: true,
    isAccessible: true,
    description:
      'Espectacular villa de diseño con más de 20 fotografías profesionales. Cada rincón ha sido cuidadosamente documentado para mostrar todos los detalles de esta propiedad excepcional. Arquitectura moderna, acabados premium y todas las comodidades.',
    socialLinks: {
      instagram: { url: 'https://www.instagram.com/reel/villa-design', likes: 5421, comments: 287 },
      facebook: { url: 'https://www.facebook.com/video/villa-design', likes: 1876, comments: 143 },
      youtube: { url: 'https://www.youtube.com/watch?v=villa-tour', likes: 3289, comments: 198 },
    },
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1515263487990-61b07816b324?w=800&q=80',
      'https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=800&q=80',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80',
      'https://images.unsplash.com/photo-1615873968403-89e068629265?w=800&q=80',
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2025-01-16T10:30:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/villa-design',
    interestedCount: 8,
    interestedLeads: [
      {
        id: 'lead-villa-001',
        name: 'Eduardo Martín',
        phone: '+34 690 123456',
        email: 'eduardo.martin@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080',
        lastContact: '2025-01-16',
        qualification: 96,
        source: 'whatsapp',
      },
      {
        id: 'lead-villa-002',
        name: 'Patricia Vega',
        phone: '+34 691 234567',
        email: 'patricia.vega@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2Mjk2NzU1MHww&ixlib=rb-4.1.0&q=80&w=1080',
        lastContact: '2025-01-15',
        qualification: 94,
        source: 'instagram',
      },
    ],
  },
  {
    id: 'prop-002',
    title: 'Ático moderno con terraza',
    price: 425000,
    pricePerM2: 5312,
    location: 'Chamartín, Madrid',
    propertyType: 'penthouse',
    operation: 'sale',
    constructedArea: 80,
    usableArea: 70,
    bedrooms: 2,
    bathrooms: 2,
    floor: '7ª planta',
    yearBuilt: 2019,
    condition: 'new',
    orientation: 'Sur-Oeste',
    energyCertification: 'A',
    hasElevator: true,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Aerotermia',
    hasParking: true,
    hasStorage: true,
    hasTerrace: true,
    hasBalcony: false,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: true,
    isFurnished: true,
    isAccessible: true,
    description:
      'Espectacular ático de última generación con terraza de 40m². Vistas panorámicas, diseño minimalista y domótica integrada. Perfecto para profesionales o parejas jóvenes.',
    socialLinks: {
      instagram: { url: 'https://www.instagram.com/reel/example2', likes: 3654, comments: 201 },
      tiktok: { url: 'https://www.tiktok.com/@example/video2', likes: 12543, comments: 432 },
    },
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-14T15:45:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example2',
    idealistaStats: {
      views: 1892,
      contacts: 67,
      favorites: 134,
    },
    interestedCount: 12,
    interestedLeads: [
      {
        id: 'lead-101',
        name: 'Lucía Ramírez',
        phone: '+34 650 123456',
        email: 'lucia.r@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1649589244330-09ca58e4fa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk2MzE0NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-14',
        qualification: 93,
        source: 'instagram',
      },
      {
        id: 'lead-102',
        name: 'Rafael Moreno',
        phone: '+34 651 234567',
        avatarUrl:
          'https://images.unsplash.com/photo-1589458223095-03eee50f0054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHByb2Zlc3Npb25hbCUyMG1hbnxlbnwxfHx8fDE3NjI5ODgzMzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-13',
        qualification: 87,
        source: 'whatsapp',
      },
      {
        id: 'lead-103',
        name: 'Beatriz Silva',
        phone: '+34 652 345678',
        email: 'beatriz.s@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1610896011476-300d6239d995?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3Jwb3JhdGUlMjB3b21hbiUyMHNtaWxpbmd8ZW58MXx8fHwxNzYzMDQ1NjQxfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-12',
        qualification: 79,
        source: 'messenger',
      },
    ],
  },
  {
    id: 'prop-003',
    title: 'Piso céntrico reformado',
    price: 295000,
    pricePerM2: 3688,
    location: 'Salamanca, Madrid',
    propertyType: 'condo',
    operation: 'sale',
    constructedArea: 80,
    usableArea: 75,
    bedrooms: 2,
    bathrooms: 1,
    floor: '3ª planta',
    yearBuilt: 1980,
    condition: 'good',
    orientation: 'Este',
    energyCertification: 'D',
    hasElevator: true,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Gas natural',
    hasParking: false,
    hasStorage: false,
    hasTerrace: false,
    hasBalcony: true,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: true,
    isFurnished: false,
    isAccessible: false,
    description:
      'Piso completamente reformado en el barrio de Salamanca. Ubicación inmejorable, rodeado de comercios, restaurantes y transporte. Ideal para inversión o vivienda habitual.',
    socialLinks: {
      instagram: {
        url: 'https://www.instagram.com/reel/piso-salamanca',
        likes: 2456,
        comments: 134,
      },
      youtube: { url: 'https://www.youtube.com/watch?v=piso-salamanca', likes: 1287, comments: 87 },
    },
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1560185007-5f0bb1866cab?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-13T09:20:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example3',
    idealistaStats: {
      views: 1245,
      contacts: 48,
      favorites: 92,
    },
    interestedCount: 8,
    interestedLeads: [
      {
        id: 'lead-201',
        name: 'Antonio Ruiz',
        phone: '+34 660 345678',
        email: 'antonio.r@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-10',
        qualification: 85,
        source: 'whatsapp',
      },
      {
        id: 'lead-202',
        name: 'Patricia Díaz',
        phone: '+34 661 456789',
        avatarUrl:
          'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2Mjk2NzU1MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-09',
        qualification: 78,
        source: 'instagram',
      },
    ],
  },
  {
    id: 'prop-004',
    title: 'Dúplex luminoso con garaje',
    price: 380000,
    pricePerM2: 3455,
    location: 'Retiro, Madrid',
    propertyType: 'duplex',
    operation: 'sale',
    constructedArea: 110,
    usableArea: 100,
    bedrooms: 3,
    bathrooms: 2,
    floor: '4ª y 5ª planta',
    yearBuilt: 2015,
    condition: 'good',
    orientation: 'Norte-Sur',
    energyCertification: 'C',
    hasElevator: true,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Calefacción central',
    hasParking: true,
    hasStorage: true,
    hasTerrace: true,
    hasBalcony: false,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: true,
    isFurnished: false,
    isAccessible: true,
    description:
      'Magnífico dúplex con doble altura y mucha luz natural. Zona muy tranquila junto al parque del Retiro. Plaza de garaje incluida.',
    socialLinks: {
      instagram: {
        url: 'https://www.instagram.com/reel/duplex-retiro',
        likes: 3789,
        comments: 198,
      },
      facebook: { url: 'https://www.facebook.com/video/duplex-retiro', likes: 1876, comments: 112 },
      tiktok: { url: 'https://www.tiktok.com/@example/duplex-retiro', likes: 15432, comments: 687 },
    },
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-16T14:20:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example4',
    idealistaStats: {
      views: 2156,
      contacts: 85,
      favorites: 167,
    },
    interestedCount: 15,
    interestedLeads: [
      {
        id: 'lead-301',
        name: 'Elena Torres',
        phone: '+34 662 789012',
        email: 'elena.t@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1649589244330-09ca58e4fa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk2MzE0NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-16',
        qualification: 92,
        source: 'whatsapp',
      },
      {
        id: 'lead-302',
        name: 'Jorge Martín',
        phone: '+34 663 890123',
        avatarUrl:
          'https://images.unsplash.com/photo-1589458223095-03eee50f0054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHByb2Zlc3Npb25hbCUyMG1hbnxlbnwxfHx8fDE3NjI5ODgzMzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-15',
        qualification: 88,
        source: 'messenger',
      },
    ],
  },
  {
    id: 'prop-005',
    title: 'Estudio moderno en Malasaña',
    price: 185000,
    pricePerM2: 4625,
    location: 'Malasaña, Madrid',
    propertyType: 'studio',
    operation: 'sale',
    constructedArea: 40,
    usableArea: 38,
    bedrooms: 1,
    bathrooms: 1,
    floor: '2ª planta',
    yearBuilt: 2021,
    condition: 'new',
    orientation: 'Oeste',
    energyCertification: 'A',
    hasElevator: true,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Bomba de calor',
    hasParking: false,
    hasStorage: false,
    hasTerrace: false,
    hasBalcony: true,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: true,
    isFurnished: true,
    isAccessible: false,
    description:
      'Estudio completamente reformado en el corazón de Malasaña. Perfecto para inversión o primera vivienda. Zona con mucha vida y todos los servicios.',
    socialLinks: {
      instagram: {
        url: 'https://www.instagram.com/reel/estudio-malasana',
        likes: 5234,
        comments: 276,
      },
      tiktok: {
        url: 'https://www.tiktok.com/@example/estudio-malasana',
        likes: 18965,
        comments: 823,
      },
    },
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-17T11:30:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example5',
    idealistaStats: {
      views: 987,
      contacts: 34,
      favorites: 67,
    },
    interestedCount: 18,
    interestedLeads: [
      {
        id: 'lead-401',
        name: 'Sofía Navarro',
        phone: '+34 664 901234',
        email: 'sofia.n@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2Mjk2NzU1MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-17',
        qualification: 89,
        source: 'instagram',
      },
      {
        id: 'lead-402',
        name: 'Miguel Ángel Castro',
        phone: '+34 665 012345',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-16',
        qualification: 81,
        source: 'tiktok',
      },
    ],
  },
  {
    id: 'prop-006',
    title: 'Local comercial en Chueca',
    price: 450000,
    pricePerM2: 5625,
    location: 'Chueca, Madrid',
    propertyType: 'commercial',
    operation: 'sale',
    constructedArea: 80,
    usableArea: 75,
    bedrooms: 0,
    bathrooms: 1,
    floor: 'Planta calle',
    yearBuilt: 1990,
    condition: 'good',
    orientation: 'Sur',
    energyCertification: 'D',
    hasElevator: false,
    hasAirConditioning: true,
    hasHeating: false,
    hasParking: false,
    hasStorage: true,
    hasTerrace: false,
    hasBalcony: false,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: false,
    isFurnished: false,
    isAccessible: true,
    description:
      'Excelente local comercial en pleno Chueca, zona de máximo tránsito. Ideal para retail, restauración o servicios. Escaparate de 6 metros. Licencia de actividad vigente.',
    socialLinks: {
      instagram: { url: 'https://www.instagram.com/reel/local-chueca', likes: 3421, comments: 187 },
      facebook: {
        url: 'https://www.facebook.com/video/local-comercial',
        likes: 2156,
        comments: 145,
      },
    },
    images: [
      'https://images.unsplash.com/photo-1759153820384-12c9ddf8bd8d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb21tZXJjaWFsJTIwc3RvcmUlMjByZXRhaWx8ZW58MXx8fHwxNzYzMTAwMTY5fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-18T09:15:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example6',
    idealistaStats: {
      views: 1543,
      contacts: 58,
      favorites: 112,
    },
    interestedCount: 9,
    interestedLeads: [
      {
        id: 'lead-501',
        name: 'Roberto Empresario',
        phone: '+34 666 123456',
        email: 'roberto.e@business.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1589458223095-03eee50f0054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHByb2Zlc3Npb25hbCUyMG1hbnxlbnwxfHx8fDE3NjI5ODgzMzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-18',
        qualification: 94,
        source: 'whatsapp',
      },
      {
        id: 'lead-502',
        name: 'Carmen Inversora',
        phone: '+34 667 234567',
        email: 'carmen.i@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1649589244330-09ca58e4fa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk2MzE0NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-17',
        qualification: 87,
        source: 'messenger',
      },
    ],
  },
  {
    id: 'prop-007',
    title: 'Terreno urbano Las Rozas',
    price: 320000,
    pricePerM2: 640,
    location: 'Las Rozas, Madrid',
    propertyType: 'land',
    operation: 'sale',
    constructedArea: 500,
    usableArea: 500,
    bedrooms: 0,
    bathrooms: 0,
    yearBuilt: 0,
    orientation: 'Sur-Este',
    energyCertification: 'pending',
    hasElevator: false,
    hasAirConditioning: false,
    hasHeating: false,
    hasParking: false,
    hasStorage: false,
    hasTerrace: false,
    hasBalcony: false,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: false,
    isFurnished: false,
    isAccessible: false,
    description:
      'Parcela urbana de 500m² en zona residencial consolidada. Edificabilidad 0.3. Todos los servicios disponibles. Ideal para construcción de vivienda unifamiliar. Vistas despejadas.',
    socialLinks: {
      youtube: {
        url: 'https://www.youtube.com/watch?v=terreno-las-rozas',
        likes: 1543,
        comments: 98,
      },
      facebook: { url: 'https://www.facebook.com/video/terreno-urbano', likes: 987, comments: 76 },
    },
    images: [
      'https://images.unsplash.com/photo-1629814531614-497f7757f7b8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlbXB0eSUyMGxhbmQlMjBwbG90fGVufDF8fHx8MTc2MzEwMDE2OXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-19T13:45:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example7',
    idealistaStats: {
      views: 876,
      contacts: 29,
      favorites: 54,
    },
    interestedCount: 6,
    interestedLeads: [
      {
        id: 'lead-601',
        name: 'Fernando Constructor',
        phone: '+34 668 345678',
        email: 'fernando.c@construcciones.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-19',
        qualification: 91,
        source: 'whatsapp',
      },
      {
        id: 'lead-602',
        name: 'Isabel Promotora',
        phone: '+34 669 456789',
        avatarUrl:
          'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2Mjk2NzU1MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-18',
        qualification: 83,
        source: 'instagram',
      },
    ],
  },
  {
    id: 'prop-008',
    title: 'Apartamento junto a metro',
    price: 240000,
    pricePerM2: 3429,
    location: 'Carabanchel, Madrid',
    propertyType: 'apartment',
    operation: 'sale',
    constructedArea: 70,
    usableArea: 65,
    bedrooms: 2,
    bathrooms: 1,
    floor: '1ª planta',
    yearBuilt: 2010,
    condition: 'good',
    orientation: 'Norte',
    energyCertification: 'E',
    hasElevator: true,
    hasAirConditioning: false,
    hasHeating: true,
    heatingType: 'Gas natural',
    hasParking: false,
    hasStorage: false,
    hasTerrace: false,
    hasBalcony: true,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: true,
    isFurnished: false,
    isAccessible: true,
    description:
      'Apartamento bien distribuido a 2 minutos del metro. Zona tranquila con todos los servicios. Perfecto para primera compra o inversión.',
    socialLinks: {
      instagram: {
        url: 'https://www.instagram.com/reel/apartamento-carabanchel',
        likes: 1876,
        comments: 112,
      },
      tiktok: {
        url: 'https://www.tiktok.com/@example/apartamento-metro',
        likes: 9876,
        comments: 432,
      },
    },
    images: [
      'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-20T10:00:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example8',
    idealistaStats: {
      views: 1432,
      contacts: 56,
      favorites: 98,
    },
    interestedCount: 11,
    interestedLeads: [
      {
        id: 'lead-701',
        name: 'Javier Primerizo',
        phone: '+34 670 567890',
        email: 'javier.p@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1589458223095-03eee50f0054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHByb2Zlc3Npb25hbCUyMG1hbnxlbnwxfHx8fDE3NjI5ODgzMzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-20',
        qualification: 86,
        source: 'tiktok',
      },
      {
        id: 'lead-702',
        name: 'Mónica Pérez',
        phone: '+34 671 678901',
        avatarUrl:
          'https://images.unsplash.com/photo-1649589244330-09ca58e4fa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk2MzE0NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-19',
        qualification: 79,
        source: 'whatsapp',
      },
    ],
  },
  {
    id: 'prop-009',
    title: 'Villa con piscina Majadahonda',
    price: 1200000,
    pricePerM2: 3636,
    location: 'Majadahonda, Madrid',
    propertyType: 'house',
    operation: 'sale',
    constructedArea: 330,
    usableArea: 300,
    bedrooms: 5,
    bathrooms: 4,
    floor: 'Planta baja + 2',
    yearBuilt: 2018,
    condition: 'new',
    orientation: 'Sur',
    energyCertification: 'A',
    hasElevator: false,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Geotermia',
    hasParking: true,
    hasStorage: true,
    hasTerrace: true,
    hasBalcony: false,
    hasGarden: true,
    hasPool: true,
    hasBuiltInWardrobes: true,
    isFurnished: false,
    isAccessible: true,
    description:
      'Impresionante villa de diseño moderno con todas las comodidades. Jardín de 800m² con piscina climatizada. Zona premium cerca de colegios internacionales.',
    socialLinks: {
      instagram: {
        url: 'https://www.instagram.com/reel/villa-majadahonda',
        likes: 4123,
        comments: 234,
      },
      youtube: { url: 'https://www.youtube.com/watch?v=villa-tour', likes: 2876, comments: 167 },
      tiktok: {
        url: 'https://www.tiktok.com/@example/villa-majadahonda',
        likes: 18765,
        comments: 623,
      },
    },
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-21T16:30:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example9',
    idealistaStats: {
      views: 2987,
      contacts: 98,
      favorites: 234,
    },
    interestedCount: 7,
    interestedLeads: [
      {
        id: 'lead-801',
        name: 'Ricardo VIP',
        phone: '+34 672 789012',
        email: 'ricardo.vip@luxury.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-21',
        qualification: 96,
        source: 'whatsapp',
      },
      {
        id: 'lead-802',
        name: 'Valentina Ejecutiva',
        phone: '+34 673 890123',
        email: 'valentina.e@corporate.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2Mjk2NzU1MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-20',
        qualification: 93,
        source: 'instagram',
      },
    ],
  },
  {
    id: 'prop-010',
    title: 'Oficina diáfana en Azca',
    price: 550000,
    pricePerM2: 5500,
    location: 'Azca, Madrid',
    propertyType: 'commercial',
    operation: 'sale',
    constructedArea: 100,
    usableArea: 95,
    bedrooms: 0,
    bathrooms: 2,
    floor: '10ª planta',
    yearBuilt: 2005,
    condition: 'good',
    orientation: 'Oeste',
    energyCertification: 'C',
    hasElevator: true,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Central',
    hasParking: true,
    hasStorage: false,
    hasTerrace: false,
    hasBalcony: false,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: false,
    isFurnished: false,
    isAccessible: true,
    description:
      'Oficina diáfana en edificio emblemático de Azca. Excelente ubicación empresarial. Incluye plaza de garaje. Ideal para empresas tecnológicas o servicios profesionales.',
    images: [
      'https://images.unsplash.com/photo-1758691736933-bb0f88fe2e0c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBvZmZpY2UlMjBjb21tZXJjaWFsfGVufDF8fHx8MTc2MzEwMDE3MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-22T12:00:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example10',
    idealistaStats: {
      views: 745,
      contacts: 23,
      favorites: 45,
    },
    interestedCount: 5,
    interestedLeads: [
      {
        id: 'lead-901',
        name: 'Empresa Tech SL',
        phone: '+34 674 901234',
        email: 'contacto@empresatech.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1589458223095-03eee50f0054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHByb2Zlc3Npb25hbCUyMG1hbnxlbnwxfHx8fDE3NjI5ODgzMzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-22',
        qualification: 88,
        source: 'messenger',
      },
    ],
  },
  {
    id: 'prop-011',
    title: 'Piso para reformar Gran Vía',
    price: 350000,
    pricePerM2: 3889,
    location: 'Gran Vía, Madrid',
    propertyType: 'condo',
    operation: 'sale',
    constructedArea: 90,
    usableArea: 85,
    bedrooms: 3,
    bathrooms: 1,
    floor: '5ª planta',
    yearBuilt: 1950,
    condition: 'to-renovate',
    orientation: 'Sur',
    energyCertification: 'G',
    hasElevator: true,
    hasAirConditioning: false,
    hasHeating: true,
    heatingType: 'Radiadores eléctricos',
    hasParking: false,
    hasStorage: false,
    hasTerrace: false,
    hasBalcony: true,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: false,
    isFurnished: false,
    isAccessible: false,
    description:
      'Piso con mucho potencial en plena Gran Vía. Techos altos y balcones a la calle. Perfecto proyecto de reforma para crear una vivienda única o inversión turística.',
    images: [
      'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&q=80',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-23T14:15:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example11',
    idealistaStats: {
      views: 1678,
      contacts: 61,
      favorites: 124,
    },
    interestedCount: 14,
    interestedLeads: [
      {
        id: 'lead-1001',
        name: 'Alberto Reformista',
        phone: '+34 675 012345',
        email: 'alberto.r@reformas.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-23',
        qualification: 84,
        source: 'whatsapp',
      },
      {
        id: 'lead-1002',
        name: 'Cristina Inversora',
        phone: '+34 676 123456',
        avatarUrl:
          'https://images.unsplash.com/photo-1649589244330-09ca58e4fa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk2MzE0NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-22',
        qualification: 91,
        source: 'instagram',
      },
    ],
  },
  {
    id: 'prop-012',
    title: 'Apartamento en alquiler Argüelles',
    price: 1800,
    pricePerM2: 25,
    location: 'Argüelles, Madrid',
    propertyType: 'apartment',
    operation: 'rent',
    constructedArea: 72,
    usableArea: 68,
    bedrooms: 2,
    bathrooms: 1,
    floor: '4ª planta',
    yearBuilt: 2000,
    condition: 'good',
    orientation: 'Este',
    energyCertification: 'D',
    hasElevator: true,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Calefacción central',
    hasParking: false,
    hasStorage: false,
    hasTerrace: false,
    hasBalcony: true,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: true,
    isFurnished: true,
    isAccessible: true,
    description:
      'Apartamento amueblado listo para entrar a vivir. Zona universitaria con excelentes conexiones. Gastos de comunidad incluidos.',
    images: [
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&q=80',
      'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-24T09:30:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example12',
    idealistaStats: {
      views: 2345,
      contacts: 89,
      favorites: 176,
    },
    interestedCount: 22,
    interestedLeads: [
      {
        id: 'lead-1101',
        name: 'Andrea Estudiante',
        phone: '+34 677 234567',
        email: 'andrea.e@univ.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2Mjk2NzU1MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-24',
        qualification: 76,
        source: 'tiktok',
      },
      {
        id: 'lead-1102',
        name: 'Luis Profesional',
        phone: '+34 678 345678',
        avatarUrl:
          'https://images.unsplash.com/photo-1589458223095-03eee50f0054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHByb2Zlc3Npb25hbCUyMG1hbnxlbnwxfHx8fDE3NjI5ODgzMzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-23',
        qualification: 82,
        source: 'whatsapp',
      },
    ],
  },
  {
    id: 'prop-013',
    title: 'Chalet adosado Tres Cantos',
    price: 495000,
    pricePerM2: 2750,
    location: 'Tres Cantos, Madrid',
    propertyType: 'house',
    operation: 'sale',
    constructedArea: 180,
    usableArea: 160,
    bedrooms: 4,
    bathrooms: 3,
    floor: 'Planta baja + 2',
    yearBuilt: 2012,
    condition: 'good',
    orientation: 'Sur-Oeste',
    energyCertification: 'C',
    hasElevator: false,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Gas natural',
    hasParking: true,
    hasStorage: true,
    hasTerrace: true,
    hasBalcony: false,
    hasGarden: true,
    hasPool: false,
    hasBuiltInWardrobes: true,
    isFurnished: false,
    isAccessible: false,
    description:
      'Chalet adosado en urbanización privada con zonas comunes, piscina comunitaria y seguridad 24h. Jardín privado. Cerca de todos los servicios.',
    images: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-25T11:45:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example13',
    idealistaStats: {
      views: 1567,
      contacts: 54,
      favorites: 103,
    },
    interestedCount: 13,
    interestedLeads: [
      {
        id: 'lead-1201',
        name: 'Familia González',
        phone: '+34 679 456789',
        email: 'familia.gonzalez@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-25',
        qualification: 89,
        source: 'whatsapp',
      },
      {
        id: 'lead-1202',
        name: 'Raquel Martín',
        phone: '+34 680 567890',
        avatarUrl:
          'https://images.unsplash.com/photo-1649589244330-09ca58e4fa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk2MzE0NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-24',
        qualification: 85,
        source: 'messenger',
      },
    ],
  },
  {
    id: 'prop-014',
    title: 'Terreno rústico Colmenar Viejo',
    price: 180000,
    pricePerM2: 18,
    location: 'Colmenar Viejo, Madrid',
    propertyType: 'land',
    operation: 'sale',
    constructedArea: 10000,
    usableArea: 10000,
    bedrooms: 0,
    bathrooms: 0,
    yearBuilt: 0,
    orientation: 'Sur',
    energyCertification: 'pending',
    hasElevator: false,
    hasAirConditioning: false,
    hasHeating: false,
    hasParking: false,
    hasStorage: false,
    hasTerrace: false,
    hasBalcony: false,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: false,
    isFurnished: false,
    isAccessible: false,
    description:
      'Terreno rústico de 10.000m² con posibilidad de construcción de casa de aperos. Agua de pozo. Ideal para uso agrícola, recreativo o inversión. Vistas a la sierra.',
    images: [
      'https://images.unsplash.com/photo-1741460801000-617e3feb65c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2YWNhbnQlMjBsYW5kJTIwZGV2ZWxvcG1lbnR8ZW58MXx8fHwxNzYzMTAwMTcwfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-26T15:20:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example14',
    idealistaStats: {
      views: 543,
      contacts: 18,
      favorites: 34,
    },
    interestedCount: 4,
    interestedLeads: [
      {
        id: 'lead-1301',
        name: 'Jaime Rural',
        phone: '+34 681 678901',
        email: 'jaime.r@agronegocios.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1589458223095-03eee50f0054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHByb2Zlc3Npb25hbCUyMG1hbnxlbnwxfHx8fDE3NjI5ODgzMzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-26',
        qualification: 73,
        source: 'instagram',
      },
    ],
  },
  {
    id: 'prop-015',
    title: 'Loft tipo industrial Tetuán',
    price: 315000,
    pricePerM2: 4500,
    location: 'Tetuán, Madrid',
    propertyType: 'studio',
    operation: 'sale',
    constructedArea: 70,
    usableArea: 68,
    bedrooms: 1,
    bathrooms: 1,
    floor: '1ª planta',
    yearBuilt: 2017,
    condition: 'new',
    orientation: 'Norte-Sur',
    energyCertification: 'B',
    hasElevator: true,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Aerotermia',
    hasParking: false,
    hasStorage: false,
    hasTerrace: false,
    hasBalcony: false,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: true,
    isFurnished: true,
    isAccessible: true,
    description:
      'Loft de diseño con acabados de lujo. Techos altos de 4 metros, vigas vistas. Cocina abierta integrada. Perfecto para profesionales creativos o parejas modernas.',
    socialLinks: {
      instagram: { url: 'https://www.instagram.com/reel/loft-tetuan', likes: 1987, comments: 124 },
    },
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1523755231516-e43fd2e8dca5?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-27T10:10:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example15',
    idealistaStats: {
      views: 1987,
      contacts: 73,
      favorites: 142,
    },
    interestedCount: 16,
    interestedLeads: [
      {
        id: 'lead-1401',
        name: 'Diana Creativa',
        phone: '+34 682 789012',
        email: 'diana.c@design.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2Mjk2NzU1MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-27',
        qualification: 90,
        source: 'instagram',
      },
      {
        id: 'lead-1402',
        name: 'Marcos Diseñador',
        phone: '+34 683 890123',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-26',
        qualification: 87,
        source: 'tiktok',
      },
    ],
  },
  {
    id: 'prop-016',
    title: 'Piso exterior en La Latina',
    price: 410000,
    pricePerM2: 5125,
    location: 'La Latina, Madrid',
    propertyType: 'condo',
    operation: 'sale',
    constructedArea: 80,
    usableArea: 75,
    bedrooms: 2,
    bathrooms: 2,
    floor: '3ª planta',
    yearBuilt: 2016,
    condition: 'new',
    orientation: 'Sur',
    energyCertification: 'B',
    hasElevator: true,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Suelo radiante',
    hasParking: false,
    hasStorage: true,
    hasTerrace: false,
    hasBalcony: true,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: true,
    isFurnished: false,
    isAccessible: true,
    description:
      'Piso completamente exterior en el corazón de La Latina. Edificio rehabilitado con fachada histórica. Zona de máximo encanto con todos los servicios.',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
      'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-28T13:50:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example16',
    idealistaStats: {
      views: 2234,
      contacts: 81,
      favorites: 159,
    },
    interestedCount: 19,
    interestedLeads: [
      {
        id: 'lead-1501',
        name: 'Natalia Sánchez',
        phone: '+34 684 901234',
        email: 'natalia.s@email.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1649589244330-09ca58e4fa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk2MzE0NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-28',
        qualification: 88,
        source: 'whatsapp',
      },
      {
        id: 'lead-1502',
        name: 'Pedro López',
        phone: '+34 685 012345',
        avatarUrl:
          'https://images.unsplash.com/photo-1589458223095-03eee50f0054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHByb2Zlc3Npb25hbCUyMG1hbnxlbnwxfHx8fDE3NjI5ODgzMzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-27',
        qualification: 83,
        source: 'messenger',
      },
    ],
  },
  {
    id: 'prop-017',
    title: 'Penthouse con vistas Castellana',
    price: 1850000,
    pricePerM2: 13214,
    location: 'Castellana, Madrid',
    propertyType: 'penthouse',
    operation: 'sale',
    constructedArea: 140,
    usableArea: 120,
    bedrooms: 3,
    bathrooms: 3,
    floor: 'Última planta',
    yearBuilt: 2022,
    condition: 'new',
    orientation: 'Sur',
    energyCertification: 'A',
    hasElevator: true,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Aerotermia',
    hasParking: true,
    hasStorage: true,
    hasTerrace: true,
    hasBalcony: false,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: true,
    isFurnished: true,
    isAccessible: true,
    description:
      'Espectacular penthouse de lujo con terraza de 80m² y vistas 360º. Acabados premium, domótica avanzada. Edificio exclusivo con conserje. Dos plazas de garaje.',
    socialLinks: {
      instagram: {
        url: 'https://www.instagram.com/reel/penthouse-castellana',
        likes: 7865,
        comments: 412,
      },
      facebook: {
        url: 'https://www.facebook.com/video/penthouse-castellana',
        likes: 3421,
        comments: 276,
      },
      youtube: { url: 'https://www.youtube.com/watch?v=luxury-tour', likes: 5432, comments: 321 },
      tiktok: {
        url: 'https://www.tiktok.com/@example/penthouse-luxury',
        likes: 23456,
        comments: 891,
      },
    },
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-29T16:00:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example17',
    idealistaStats: {
      views: 3421,
      contacts: 112,
      favorites: 267,
    },
    interestedCount: 10,
    interestedLeads: [
      {
        id: 'lead-1601',
        name: 'Inversores Luxury Group',
        phone: '+34 686 123456',
        email: 'contact@luxurygroup.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-29',
        qualification: 97,
        source: 'whatsapp',
      },
      {
        id: 'lead-1602',
        name: 'Victoria Elite',
        phone: '+34 687 234567',
        email: 'victoria@elite.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2Mjk2NzU1MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-28',
        qualification: 95,
        source: 'instagram',
      },
    ],
  },
  {
    id: 'prop-018',
    title: 'Casa rústica con finca Cercedilla',
    price: 680000,
    pricePerM2: 2833,
    location: 'Cercedilla, Madrid',
    propertyType: 'house',
    operation: 'sale',
    constructedArea: 240,
    usableArea: 220,
    bedrooms: 4,
    bathrooms: 3,
    floor: 'Planta baja + 1',
    yearBuilt: 1995,
    condition: 'good',
    orientation: 'Sur-Este',
    energyCertification: 'E',
    hasElevator: false,
    hasAirConditioning: false,
    hasHeating: true,
    heatingType: 'Chimenea + radiadores',
    hasParking: true,
    hasStorage: true,
    hasTerrace: true,
    hasBalcony: false,
    hasGarden: true,
    hasPool: false,
    hasBuiltInWardrobes: false,
    isFurnished: false,
    isAccessible: false,
    description:
      'Encantadora casa rústica con finca de 2.000m² en la sierra. Entorno natural privilegiado. Ideal como segunda residencia o vivienda permanente para amantes de la naturaleza.',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
      'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-30T12:30:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example18',
    idealistaStats: {
      views: 1123,
      contacts: 38,
      favorites: 72,
    },
    interestedCount: 8,
    interestedLeads: [
      {
        id: 'lead-1701',
        name: 'Francisco Sierra',
        phone: '+34 688 345678',
        email: 'francisco.s@montaña.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1589458223095-03eee50f0054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHByb2Zlc3Npb25hbCUyMG1hbnxlbnwxfHx8fDE3NjI5ODgzMzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-30',
        qualification: 81,
        source: 'messenger',
      },
      {
        id: 'lead-1702',
        name: 'Gloria Naturalista',
        phone: '+34 689 456789',
        avatarUrl:
          'https://images.unsplash.com/photo-1649589244330-09ca58e4fa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk2MzE0NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-29',
        qualification: 77,
        source: 'whatsapp',
      },
    ],
  },
  {
    id: 'prop-019',
    title: 'Apartamento en alquiler Moncloa',
    price: 1500,
    pricePerM2: 21,
    location: 'Moncloa, Madrid',
    propertyType: 'apartment',
    operation: 'rent',
    constructedArea: 70,
    usableArea: 65,
    bedrooms: 2,
    bathrooms: 1,
    floor: '3ª planta',
    yearBuilt: 2008,
    condition: 'good',
    orientation: 'Oeste',
    energyCertification: 'D',
    hasElevator: true,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Calefacción central',
    hasParking: false,
    hasStorage: false,
    hasTerrace: false,
    hasBalcony: true,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: true,
    isFurnished: true,
    isAccessible: true,
    description:
      'Apartamento totalmente amueblado cerca de Ciudad Universitaria. Perfecto para estudiantes o profesores. Bien comunicado con metro y autobuses.',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&q=80',
    ],
    status: 'available',
    updatedAt: '2024-01-31T14:45:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example19',
    idealistaStats: {
      views: 2876,
      contacts: 95,
      favorites: 187,
    },
    interestedCount: 26,
    interestedLeads: [
      {
        id: 'lead-1801',
        name: 'Susana Profesora',
        phone: '+34 690 567890',
        email: 'susana.p@universidad.edu',
        avatarUrl:
          'https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMGhlYWRzaG90fGVufDF8fHx8MTc2Mjk2NzU1MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-31',
        qualification: 84,
        source: 'whatsapp',
      },
      {
        id: 'lead-1802',
        name: 'Tomás Investigador',
        phone: '+34 691 678901',
        avatarUrl:
          'https://images.unsplash.com/photo-1624835567150-0c530a20d8cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBidXNpbmVzcyUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk0NDA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-30',
        qualification: 79,
        source: 'instagram',
      },
    ],
  },
  {
    id: 'prop-020',
    title: 'Local comercial esquina Atocha',
    price: 850000,
    pricePerM2: 6071,
    location: 'Atocha, Madrid',
    propertyType: 'commercial',
    operation: 'sale',
    constructedArea: 140,
    usableArea: 135,
    bedrooms: 0,
    bathrooms: 2,
    floor: 'Planta calle',
    yearBuilt: 2001,
    condition: 'good',
    orientation: 'Este-Sur',
    energyCertification: 'C',
    hasElevator: false,
    hasAirConditioning: true,
    hasHeating: true,
    heatingType: 'Central',
    hasParking: false,
    hasStorage: true,
    hasTerrace: false,
    hasBalcony: false,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: false,
    isFurnished: false,
    isAccessible: true,
    description:
      'Local comercial en esquina con dos escaparates y gran visibilidad. Zona de alto tránsito cerca de Atocha. Ideal para hostelería, retail premium o servicios financieros.',
    images: [
      'https://images.unsplash.com/photo-1759153820384-12c9ddf8bd8d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb21tZXJjaWFsJTIwc3RvcmUlMjByZXRhaWx8ZW58MXx8fHwxNzYzMTAwMTY5fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
    ],
    status: 'unavailable',
    updatedAt: '2024-02-01T10:20:00Z',
    idealistaUrl: 'https://www.idealista.com/inmueble/example20',
    idealistaStats: {
      views: 1765,
      contacts: 64,
      favorites: 128,
    },
    interestedCount: 12,
    interestedLeads: [
      {
        id: 'lead-1901',
        name: 'Grupo Hostelero Madrid',
        phone: '+34 692 789012',
        email: 'info@grupohostelero.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1589458223095-03eee50f0054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHByb2Zlc3Npb25hbCUyMG1hbnxlbnwxfHx8fDE3NjI5ODgzMzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-02-01',
        qualification: 93,
        source: 'whatsapp',
      },
      {
        id: 'lead-1902',
        name: 'Cadena Retail Internacional',
        phone: '+34 693 890123',
        email: 'expansion@retailintl.com',
        avatarUrl:
          'https://images.unsplash.com/photo-1649589244330-09ca58e4fa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjB3b21hbiUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjk2MzE0NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        lastContact: '2025-01-31',
        qualification: 89,
        source: 'messenger',
      },
    ],
  },
  // Propiedades del chat de leads
  {
    id: '1',
    title: 'Apartamento moderno en el centro',
    price: 245000,
    pricePerM2: 3267,
    location: 'Centro',
    propertyType: 'condo',
    operation: 'sale',
    constructedArea: 75,
    usableArea: 75,
    bedrooms: 2,
    bathrooms: 1,
    yearBuilt: 2021,
    condition: 'good',
    hasElevator: true,
    hasAirConditioning: true,
    hasHeating: true,
    hasParking: false,
    hasStorage: false,
    hasTerrace: false,
    hasBalcony: false,
    hasGarden: false,
    hasPool: false,
    hasBuiltInWardrobes: false,
    isFurnished: false,
    isAccessible: true,
    description:
      'Espectacular apartamento moderno ubicado en pleno centro de la ciudad. Completamente reformado con materiales de alta calidad y un diseño contemporáneo.',
    images: [
      'https://images.unsplash.com/photo-1594873604892-b599f847e859?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBhcGFydG1lbnQlMjBpbnRlcmlvcnxlbnwxfHx8fDE3NjI0OTcyNDJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1556912167-f556f1f39fdf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBraXRjaGVufGVufDF8fHx8MTc2MjQ3MDUzN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    status: 'available',
    updatedAt: '2025-01-20T10:00:00Z',
  },
  {
    id: '2',
    title: 'Casa de lujo con jardín',
    price: 520000,
    pricePerM2: 2364,
    location: 'Zona Norte',
    propertyType: 'house',
    operation: 'sale',
    constructedArea: 220,
    usableArea: 220,
    bedrooms: 4,
    bathrooms: 3,
    yearBuilt: 2020,
    condition: 'good',
    hasElevator: false,
    hasAirConditioning: true,
    hasHeating: true,
    hasParking: true,
    hasStorage: true,
    hasTerrace: false,
    hasBalcony: false,
    hasGarden: true,
    hasPool: true,
    hasBuiltInWardrobes: true,
    isFurnished: false,
    isAccessible: true,
    description:
      'Impresionante casa unifamiliar de lujo en la zona norte de la ciudad. Diseño arquitectónico exclusivo con acabados premium en cada detalle.',
    images: [
      'https://images.unsplash.com/photo-1711098256574-7b497260cdc9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBob3VzZSUyMGdhcmRlbnxlbnwxfHx8fDE3NjI0NTgzNTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1638885930125-85350348d266?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBsaXZpbmclMjByb29tfGVufDF8fHx8MTc2MjQ3MjE2MHww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    status: 'available',
    updatedAt: '2025-01-20T10:00:00Z',
  },
  {
    id: '7',
    title: 'Villa mediterránea con piscina',
    price: 850000,
    pricePerM2: 2237,
    location: 'Urbanización Las Colinas',
    propertyType: 'house',
    operation: 'sale',
    constructedArea: 380,
    usableArea: 380,
    bedrooms: 5,
    bathrooms: 4,
    yearBuilt: 2019,
    condition: 'new',
    hasElevator: false,
    hasAirConditioning: true,
    hasHeating: true,
    hasParking: true,
    hasStorage: true,
    hasTerrace: true,
    hasBalcony: false,
    hasGarden: true,
    hasPool: true,
    hasBuiltInWardrobes: true,
    isFurnished: false,
    isAccessible: true,
    description:
      'Exclusiva villa mediterránea situada en la prestigiosa Urbanización Las Colinas. Arquitectura mediterránea de lujo con espacios diseñados para el confort.',
    images: [
      'https://images.unsplash.com/photo-1757439402101-55d1da381e70?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpdGVycmFuZWFuJTIwdmlsbGElMjBwb29sfGVufDF8fHx8MTc2MjQ3MzQ4Mnww&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1638885930125-85350348d266?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBsaXZpbmclMjByb29tfGVufDF8fHx8MTc2MjQ3MjE2MHww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    status: 'available',
    updatedAt: '2025-01-20T10:00:00Z',
  },
  {
    id: '10',
    title: 'Chalé rústico en las afueras',
    price: 280000,
    pricePerM2: 1556,
    location: 'Piloña - Villarcazu',
    propertyType: 'house',
    operation: 'sale',
    constructedArea: 180,
    usableArea: 180,
    bedrooms: 3,
    bathrooms: 2,
    yearBuilt: 1995,
    condition: 'good',
    hasElevator: false,
    hasAirConditioning: false,
    hasHeating: true,
    hasParking: true,
    hasStorage: true,
    hasTerrace: false,
    hasBalcony: false,
    hasGarden: true,
    hasPool: false,
    hasBuiltInWardrobes: false,
    isFurnished: false,
    isAccessible: false,
    description:
      'Magnífica casa rústica en Piloña - Villarcazu, con vistas panorámicas a la montaña. Construcción tradicional asturiana reformada.',
    images: [
      'https://images.unsplash.com/photo-1646775815157-8645b5af4e08?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBydXN0aWMlMjBob3VzZSUyMGV4dGVyaW9yfGVufDF8fHx8MTc2MjUwNjU4NHww&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3p5JTIwbGl2aW5nJTIwcm9vbXxlbnwxfHx8fDE3NjI0OTI3MjN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    status: 'available',
    updatedAt: '2025-01-20T10:00:00Z',
  },
  {
    id: '11',
    title: 'Apartamento en primera línea de playa',
    price: 425000,
    pricePerM2: 3400,
    location: 'Primera línea de playa',
    propertyType: 'apartment',
    operation: 'sale',
    constructedArea: 125,
    usableArea: 125,
    bedrooms: 3,
    bathrooms: 2,
    yearBuilt: 2018,
    condition: 'new',
    hasElevator: true,
    hasAirConditioning: true,
    hasHeating: true,
    hasParking: true,
    hasStorage: false,
    hasTerrace: true,
    hasBalcony: false,
    hasGarden: false,
    hasPool: true,
    hasBuiltInWardrobes: true,
    isFurnished: false,
    isAccessible: true,
    description:
      'Extraordinario apartamento de lujo en primera línea de playa con vistas espectaculares al mar. Complejo con piscina y seguridad 24h.',
    images: [
      'https://images.unsplash.com/photo-1759082105425-3a426d3d7275?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWFjaCUyMGFwYXJ0bWVudCUyMHZpZXd8ZW58MXx8fHwxNzYyNTE4NzY1fDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1594873604892-b599f847e859?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBhcGFydG1lbnQlMjBpbnRlcmlvcnxlbnwxfHx8fDE3NjI0OTcyNDJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    status: 'available',
    updatedAt: '2025-01-20T10:00:00Z',
  },
];

// Función helper para saber qué características aplican a cada tipo de propiedad
export function getPropertyTypeFeatures(propertyType: Property['propertyType']) {
  const features = {
    hasBedrooms: true,
    hasBathrooms: true,
    hasFloor: true,
    hasYearBuilt: true,
    hasCondition: true,
    hasOrientation: true,
    hasEnergyRating: true,
    hasElevator: true,
    hasAirConditioning: true,
    hasHeating: true,
    hasParking: true,
    hasStorage: true,
    hasTerrace: true,
    hasBalcony: true,
    hasGarden: true,
    hasPool: true,
    hasWardrobes: true,
    hasFurnished: true,
    hasAccessible: true,
  };

  // Terrenos: solo área, orientación y energía
  if (propertyType === 'land') {
    return {
      ...features,
      hasBedrooms: false,
      hasBathrooms: false,
      hasFloor: false,
      hasYearBuilt: false,
      hasCondition: false,
      hasElevator: false,
      hasAirConditioning: false,
      hasHeating: false,
      hasStorage: false,
      hasTerrace: false,
      hasBalcony: false,
      hasWardrobes: false,
      hasFurnished: false,
    };
  }

  // Naves: sin habitaciones, sin balcón
  if (propertyType === 'warehouse') {
    return {
      ...features,
      hasBedrooms: false,
      hasBathrooms: false,
      hasBalcony: false,
      hasWardrobes: false,
      hasFurnished: false,
      hasGarden: false,
      hasPool: false,
    };
  }

  // Garajes: solo área y acceso
  if (propertyType === 'garage') {
    return {
      ...features,
      hasBedrooms: false,
      hasBathrooms: false,
      hasYearBuilt: false,
      hasCondition: false,
      hasOrientation: false,
      hasElevator: false,
      hasAirConditioning: false,
      hasHeating: false,
      hasStorage: false,
      hasTerrace: false,
      hasBalcony: false,
      hasGarden: false,
      hasPool: false,
      hasWardrobes: false,
      hasFurnished: false,
    };
  }

  // Trasteros: solo área básica
  if (propertyType === 'storage') {
    return {
      ...features,
      hasBedrooms: false,
      hasBathrooms: false,
      hasYearBuilt: false,
      hasCondition: false,
      hasOrientation: false,
      hasElevator: false,
      hasAirConditioning: false,
      hasHeating: false,
      hasParking: false,
      hasStorage: false,
      hasTerrace: false,
      hasBalcony: false,
      hasGarden: false,
      hasPool: false,
      hasWardrobes: false,
      hasFurnished: false,
    };
  }

  // Oficinas: sin habitaciones
  if (propertyType === 'office') {
    return {
      ...features,
      hasBedrooms: false,
      hasBathrooms: true,
      hasBalcony: false,
      hasGarden: false,
      hasPool: false,
      hasWardrobes: false,
    };
  }

  // Locales comerciales: sin habitaciones
  if (propertyType === 'commercial') {
    return {
      ...features,
      hasBedrooms: false,
      hasBathrooms: true,
      hasBalcony: false,
      hasGarden: false,
      hasPool: false,
      hasWardrobes: false,
    };
  }

  // Propiedades residenciales: todas las características
  return features;
}

// Función para obtener una propiedad por ID
export function getPropertyById(id: string): Property | undefined {
  // Primero intentar obtener desde localStorage (propiedades editadas)
  const savedProperties = localStorage.getItem('realmaker_properties');
  if (savedProperties) {
    try {
      const properties = JSON.parse(savedProperties);
      const found = properties.find((prop: Property) => prop.id === id);
      if (found) return found;
    } catch (error) {
      console.error('Error al parsear propiedades guardadas:', error);
    }
  }

  // Si no está en localStorage, devolver la del mock
  return MOCK_PROPERTIES.find((prop) => prop.id === id);
}
